<a href="https://colab.research.google.com/github/muhamadarifna/Portofolio-Arif/blob/main/ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ETL - Extract Transform and Load

*   ETL is process of obtaining the data, cleaning the data  (extracted), wrangling the data (transformed), and then it is placed into a user-friendly data structure like a data frame (loaded).
---
*   First we will set up a link to an API and make calls to it.
*   The API being used here is ROM Exchanga API; it is publicly available that has been keeping track of the market price of items on two different servers of the game Ragnarok Mobile.
*   API’s are a very common set of tools and protocols that allow interaction between applications, code, projects and machines.
*   An API is another kind of user interface but the user is not a human being, it’s a machine( a software application running on your computer for example).
*   It allows a machine to access information and is designed so it can do it easily.
*   If one device or machine wants to talk to another or get information from another it can do this through an API.
* The action of sending a request to an endpoint on a server is known as making a call to an API.
* An endpoint is a destination perhaps on a server or service.
*   Requests allows you to send HTTP/1.1 requests extremely easily. There’s no need to manually add query strings to your URLs, or to form-encode your POST data.

In [1]:
import requests

In [ ]:
pip install --upgrade requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Collecting requests
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2025.8.3)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 2.8 MB/s eta 0:00:00
Installing collected packages: requests
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.32.5 which is incompatible.
Successfully installed requests-2.32.5

* We declare ‘r’ as our response object. we use the .get() method from the requests library to obtain a response from the URL of our choice

In [ ]:
#romexchange website
r = requests.get('https://www.romexchange.com/')

* status code command is used to see what kind of response we have received.

In [ ]:
#see what kind of a response we got using the status code command
r.status_code

406

In [ ]:
#content-type we’re expecting is going to be recognised as application/json
url = 'https://www.romexchange.com/'

headers = { 'Content-type': 'application/json'}

In [ ]:
r = requests.get(url, headers = headers)

In [ ]:
#add the User-Agent change found in that solution code to our headers params
url = 'https://www.romexchange.com/'

headers = {'User-Agent': 'XY','Content-type': 'application/json'}
r = requests.get(url, headers=headers)

In [ ]:
r.status_code

200

In [ ]:
url = 'https://www.romexchange.com/api?item=mastela&exact=false'
headers = {'User-Agent': 'XY', 'Content-type': 'application/json'}

r = requests.get(url, headers = headers)
r.status_code

200

In [ ]:
r.text

'[{"name":"Mastela Fruit","type":8,"image":null,"global_sea_diff":-31.10000000000000142108547152020037174224853515625,"global":{"week":{"data":[{"snap":true,"price":1330930,"time":"2020-01-07T08:26:57Z"},{"snap":true,"price":1271953,"time":"2020-01-08T08:13:52Z"},{"snap":true,"price":1103197,"time":"2020-01-09T08:31:43Z"},{"snap":true,"price":1239346,"time":"2020-01-11T08:33:59Z"},{"snap":true,"price":1062386,"time":"2020-01-14T08:20:20Z"}],"change":-20.199999999999999289457264239899814128875732421875},"latest":1062386,"latest_time":"2020-01-14T08:20:20Z"},"sea":{"week":{"data":[{"snap":false,"price":699973,"time":"2020-01-07T11:08:25Z"},{"snap":false,"price":674722,"time":"2020-01-08T10:52:15Z"},{"snap":false,"price":665887,"time":"2020-01-09T11:24:06Z"},{"snap":true,"price":661969,"time":"2020-01-10T11:48:26Z"},{"snap":true,"price":693119,"time":"2020-01-11T11:35:06Z"},{"snap":false,"price":731711,"time":"2020-01-14T11:03:14Z"}],"change":4.5},"latest":731711,"latest_time":"2020-01-14T11:03:14Z"}},{"name":"Seed of Mastela","type":11,"image":null,"global_sea_diff":-31.800000000000000710542735760100185871124267578125,"global":{"week":{"data":[{"snap":false,"price":251375,"time":"2020-01-08T08:20:23Z"},{"snap":false,"price":217693,"time":"2020-01-09T08:38:57Z"},{"snap":false,"price":268589,"time":"2020-01-10T08:35:46Z"},{"snap":false,"price":245010,"time":"2020-01-11T08:41:27Z"},{"snap":false,"price":215300,"time":"2020-01-12T08:34:31Z"},{"snap":false,"price":210296,"time":"2020-01-13T08:35:10Z"},{"snap":false,"price":209658,"time":"2020-01-14T08:26:39Z"}],"change":-16.60000000000000142108547152020037174224853515625},"latest":209658,"latest_time":"2020-01-14T08:26:39Z"},"sea":{"week":{"data":[{"snap":false,"price":131573,"time":"2020-01-08T10:58:01Z"},{"snap":false,"price":129889,"time":"2020-01-09T11:30:09Z"},{"snap":false,"price":129093,"time":"2020-01-10T11:54:12Z"},{"snap":true,"price":135391,"time":"2020-01-11T11:40:56Z"},{"snap":true,"price":142009,"time":"2020-01-12T11:15:55Z"},{"snap":false,"price":147192,"time":"2020-01-13T11:24:25Z"},{"snap":false,"price":143017,"time":"2020-01-14T11:10:36Z"}],"change":8.699999999999999289457264239899814128875732421875},"latest":143017,"latest_time":"2020-01-14T11:10:36Z"}}]'

* The above data is a list of dictionaries. It is difficult to read this. We can clean this up using JavaScript Object Notation (JSON).

# EXTRACT

* The JSON decoder is inbuilt into the Python request library.
* It will allow us to observe the request payload (the returned data ) in a more visually pleasing way.

In [ ]:
#JSONify the data
j = r.json()

In [ ]:
type(j)

list

In [ ]:
j

[{'global': {'latest': 1062386,
   'latest_time': '2020-01-14T08:20:20Z',
   'week': {'change': -20.2,
    'data': [{'price': 1330930, 'snap': True, 'time': '2020-01-07T08:26:57Z'},
     {'price': 1271953, 'snap': True, 'time': '2020-01-08T08:13:52Z'},
     {'price': 1103197, 'snap': True, 'time': '2020-01-09T08:31:43Z'},
     {'price': 1239346, 'snap': True, 'time': '2020-01-11T08:33:59Z'},
     {'price': 1062386, 'snap': True, 'time': '2020-01-14T08:20:20Z'}]}},
  'global_sea_diff': -31.1,
  'image': None,
  'name': 'Mastela Fruit',
  'sea': {'latest': 731711,
   'latest_time': '2020-01-14T11:03:14Z',
   'week': {'change': 4.5,
    'data': [{'price': 699973, 'snap': False, 'time': '2020-01-07T11:08:25Z'},
     {'price': 674722, 'snap': False, 'time': '2020-01-08T10:52:15Z'},
     {'price': 665887, 'snap': False, 'time': '2020-01-09T11:24:06Z'},
     {'price': 661969, 'snap': True, 'time': '2020-01-10T11:48:26Z'},
     {'price': 693119, 'snap': True, 'time': '2020-01-11T11:35:06Z'},
     {'price': 731711, 'snap': False, 'time': '2020-01-14T11:03:14Z'}]}},
  'type': 8},
 {'global': {'latest': 209658,
   'latest_time': '2020-01-14T08:26:39Z',
   'week': {'change': -16.6,
    'data': [{'price': 251375, 'snap': False, 'time': '2020-01-08T08:20:23Z'},
     {'price': 217693, 'snap': False, 'time': '2020-01-09T08:38:57Z'},
     {'price': 268589, 'snap': False, 'time': '2020-01-10T08:35:46Z'},
     {'price': 245010, 'snap': False, 'time': '2020-01-11T08:41:27Z'},
     {'price': 215300, 'snap': False, 'time': '2020-01-12T08:34:31Z'},
     {'price': 210296, 'snap': False, 'time': '2020-01-13T08:35:10Z'},
     {'price': 209658, 'snap': False, 'time': '2020-01-14T08:26:39Z'}]}},
  'global_sea_diff': -31.8,
  'image': None,
  'name': 'Seed of Mastela',
  'sea': {'latest': 143017,
   'latest_time': '2020-01-14T11:10:36Z',
   'week': {'change': 8.7,
    'data': [{'price': 131573, 'snap': False, 'time': '2020-01-08T10:58:01Z'},
     {'price': 129889, 'snap': False, 'time': '2020-01-09T11:30:09Z'},
     {'price': 129093, 'snap': False, 'time': '2020-01-10T11:54:12Z'},
     {'price': 135391, 'snap': True, 'time': '2020-01-11T11:40:56Z'},
     {'price': 142009, 'snap': True, 'time': '2020-01-12T11:15:55Z'},
     {'price': 147192, 'snap': False, 'time': '2020-01-13T11:24:25Z'},
     {'price': 143017, 'snap': False, 'time': '2020-01-14T11:10:36Z'}]}},
  'type': 11}]

In [ ]:
#first item in the list
j[0]

{'global': {'latest': 1062386,
  'latest_time': '2020-01-14T08:20:20Z',
  'week': {'change': -20.2,
   'data': [{'price': 1330930, 'snap': True, 'time': '2020-01-07T08:26:57Z'},
    {'price': 1271953, 'snap': True, 'time': '2020-01-08T08:13:52Z'},
    {'price': 1103197, 'snap': True, 'time': '2020-01-09T08:31:43Z'},
    {'price': 1239346, 'snap': True, 'time': '2020-01-11T08:33:59Z'},
    {'price': 1062386, 'snap': True, 'time': '2020-01-14T08:20:20Z'}]}},
 'global_sea_diff': -31.1,
 'image': None,
 'name': 'Mastela Fruit',
 'sea': {'latest': 731711,
  'latest_time': '2020-01-14T11:03:14Z',
  'week': {'change': 4.5,
   'data': [{'price': 699973, 'snap': False, 'time': '2020-01-07T11:08:25Z'},
    {'price': 674722, 'snap': False, 'time': '2020-01-08T10:52:15Z'},
    {'price': 665887, 'snap': False, 'time': '2020-01-09T11:24:06Z'},
    {'price': 661969, 'snap': True, 'time': '2020-01-10T11:48:26Z'},
    {'price': 693119, 'snap': True, 'time': '2020-01-11T11:35:06Z'},
    {'price': 731711, 'snap': False, 'time': '2020-01-14T11:03:14Z'}]}},
 'type': 8}

* Using the correct indexing we can ask pandas to create a data frame from the dictionary we want inside this list

In [ ]:
#ask pandas to create a data frame from the dictionary we want inside this list
import numpy as np
import pandas as pd

j[0]['name']
dfglobal = pd.DataFrame(j[0]['global']['week']['data'])
dfglobal['name'] = j[0]['name']
dfglobal['server'] = 'Global'

In [ ]:
dfglobal

   snap    price                  time           name  server
0  True  1330930  2020-01-07T08:26:57Z  Mastela Fruit  Global
1  True  1271953  2020-01-08T08:13:52Z  Mastela Fruit  Global
2  True  1103197  2020-01-09T08:31:43Z  Mastela Fruit  Global
3  True  1239346  2020-01-11T08:33:59Z  Mastela Fruit  Global
4  True  1062386  2020-01-14T08:20:20Z  Mastela Fruit  Global

# Transform

* Now, we are checking for missing values in the dataset.

In [ ]:
#Clean data
dfglobal.isna().sum()

snap      0
price     0
time      0
name      0
server    0
dtype: int64

* There are no missing values.

In [ ]:
#Making the time column a pandas date-time format
dfglobal.time = pd.to_datetime(dfglobal.time, errors='raise')

In [ ]:
dfglobal

   snap    price                      time           name  server
0  True  1330930 2020-01-07 08:26:57+00:00  Mastela Fruit  Global
1  True  1271953 2020-01-08 08:13:52+00:00  Mastela Fruit  Global
2  True  1103197 2020-01-09 08:31:43+00:00  Mastela Fruit  Global
3  True  1239346 2020-01-11 08:33:59+00:00  Mastela Fruit  Global
4  True  1062386 2020-01-14 08:20:20+00:00  Mastela Fruit  Global

* Here is a simple pandas groupby() method with an aggregate mean function to obtain insight into the average price between servers

In [ ]:
#obtain insight into the average price between servers
dfglobal.groupby('server')['price'].mean()

server
Global    1201562.4
Name: price, dtype: float64

# Load

* We are now importing sqlite3 and are creating a connection to a database.
* Doing so will automatically manifest a database.
* The cur object below is a way to fetch results and keep track of results from queries you make in the SQL language.

In [ ]:
import sqlite3
conn = sqlite3.connect('romexchange.db')
cur = conn.cursor()

* We can load the data frame we have created into an SQL table

In [ ]:
#load the data frame we have created into an SQL table
dfglobal.to_sql(name='abyss_flowers', if_exists='replace', con=conn)

* We can perform a fetchall() to check the data exists in the database

In [ ]:
#perform a fetchall() to check the data exists in the database
cur.execute("""SELECT * FROM abyss_flowers;""").fetchall()

[(0, 1, 1330930, '2020-01-07 08:26:57+00:00', 'Mastela Fruit', 'Global'),
 (1, 1, 1271953, '2020-01-08 08:13:52+00:00', 'Mastela Fruit', 'Global'),
 (2, 1, 1103197, '2020-01-09 08:31:43+00:00', 'Mastela Fruit', 'Global'),
 (3, 1, 1239346, '2020-01-11 08:33:59+00:00', 'Mastela Fruit', 'Global'),
 (4, 1, 1062386, '2020-01-14 08:20:20+00:00', 'Mastela Fruit', 'Global')]